### ISSUE TITLE
kfd offsets 

### ISSUE THREAD

**Issue by Artiks-Nasik** [34306/iPA#3]
Hi, can u please give me an ip11pro 16.6b1 kfd offset?

**Comment by KIKMAX** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Artiks-Nasik** [comment]
Ok, thanks

**Comment by KIKMAX** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
